import { config } from 'dotenv';

config();

const { POSTGRES_DB, POSTGRES_HOST, POSTGRES_PORT, POSTGRES_PASSWORD, POSTGRES_USERNAME, APP_PORT, JWT_SECRATE } = process.env;

export { POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_PORT, POSTGRES_USERNAME, APP_PORT, JWT_SECRATE };
